takeQuiz/urls.py
from django.urls import include, path
from .views import home, QuizListView, TakenQuizListView, StudentSubjectsView, take_quiz, completed_quiz, confirm_quiz

urlpatterns = [
    path('', home, name='home'),
    path('students/', include(([
        path('', QuizListView.as_view(), name = 'quiz_list'),
        path('subjects/', StudentSubjectsView.as_view(), name='student_subjects'),
        path('quiztaken/', TakenQuizListView.as_view(), name = 'taken_quiz'),
        path('quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
        path('confirm_quiz/<int:pk>/', confirm_quiz, name = 'confirm_quiz'),
        path('completed_quiz/<int:pk>/', completed_quiz, name = 'completed_quiz'),
    ], 'takeQuiz'), namespace='students')),
]

testYourKnowledge/urls.py
from django.contrib import admin
from django.urls import include, path

from takeQuiz.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('takeQuiz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
]

templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}MCQ Test{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    <style>
        .sidenav {
          height: 100%;
          width: 150px;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #0f292f;
          overflow-x: hidden;
          padding-top: 10px;
        }

        .sidenav a {
          padding: 6px 8px 6px 16px;
          text-decoration: none;
          font-size: 16px;
          color: #818181;
          display: block;
        }
    
        .sidenav a:hover {
          color: #f1f1f1;
        }

        @media screen and (max-height: 450px) {
          .sidenav {padding-top: 15px;}
          .sidenav a {font-size: 18px;}
        }
  </style>
  </head>
  <body>
    <div class="sidenav">
      <a href="{% url 'home' %}" style="padding-top: 3px;"><strong>MCQ TEST</strong></a>
      <a href="{% url 'students:quiz_list' %}" style="margin-top: 10px;">Take Test</a>
      <a href="{% url 'students:taken_quiz' %}">History</a>
    </div>
    <div id="header" class="col-lg-12" style="background-color: #0f292f; height: 35px; text-align: center;">
        {% if user.is_authenticated %}
          <span style="color: white; margin-left: 70%;">Howdy <strong style="color: blue;">{{ user.username }}</strong>!!</span>
          <a href="{% url 'logout' %}"><span style="color: white; margin-left: 2%;">Sign Out<span></a>
        {% else %}
          <a href="{% url 'login' %}"><span style="color: white; margin-left: 75%;">Log in<span></a>
          <a href="{% url 'signup' %}"><span style="color : white; margin-left: 2%;"> Sign up</span></a>
        {% endif %}
    </div>
    <div class="container my-5">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
            <div class="container">
              {% block content %}
              {% endblock %}
            </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}