takeQuiz/urls.py
from django.urls import include, path
from .views import home, QuizListView, TakenQuizListView, StudentSubjectsView, take_quiz, completed_quiz, confirm_quiz

urlpatterns = [
    path('', home, name='home'),
    path('students/', include(([
        path('', QuizListView.as_view(), name = 'quiz_list'),
        path('subjects/', StudentSubjectsView.as_view(), name='student_subjects'),
        path('quiztaken/', TakenQuizListView.as_view(), name = 'taken_quiz'),
        path('quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
        path('confirm_quiz/<int:pk>/', confirm_quiz, name = 'confirm_quiz'),
        path('completed_quiz/<int:pk>/', completed_quiz, name = 'completed_quiz'),
    ], 'takeQuiz'), namespace='students')),
]

testYourKnowledge/urls.py
from django.contrib import admin
from django.urls import include, path

from takeQuiz.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('takeQuiz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
]

takeQuiz/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from datetime import date, datetime, timedelta


class User(AbstractUser):
    is_student = models.BooleanField(default=False)


class Subject(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        html = '<span class = "badge badge-secondary" style="color: #0f292f">%s</span>' % (name)
        return mark_safe(html)


class Quiz(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateField(default=date.today(), blank=True)
    expiration_date = models.DateField(default=date.today() + timedelta(15), blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Choice', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    subjects = models.ManyToManyField(Subject, related_name='interested_students')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    correct_answer = models.IntegerField()
    total_question = models.IntegerField()
    date = models.DateField(default=date.today(), blank=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Choice, on_delete=models.CASCADE, related_name='+')

takeQuiz/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from .models import (Choice, Question, Student, StudentAnswer,
                              User, Subject)


class SignUpForm(UserCreationForm):
    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.subjects.add(*self.cleaned_data.get('subjects'))
        return user

class StudentSubjectsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('subjects', )
        widgets = {
            'subjects': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Choice.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

takeQuiz/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from .decorators import student_required
from .forms import SignUpForm, TakeQuizForm, StudentSubjectsForm
from .models import Quiz, Student, TakenQuiz, User


def home(request):
    if request.user.is_authenticated:
        return redirect('students:quiz_list')
    return render(request, 'takeQuiz/home.html')


class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:quiz_list')

@method_decorator([login_required, student_required], name='dispatch')
class StudentSubjectsView(UpdateView):
    model = Student
    form_class = StudentSubjectsForm
    template_name = 'takeQuiz/students/subjects_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'takeQuiz/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_subjects = student.subjects.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(subject__in=student_subjects) \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'takeQuiz/students/taken_quiz.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz') \
            .order_by('quiz__name')
        return queryset


@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    unanswered_questions_count= unanswered_questions.count()
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    TakenQuiz.objects.create(student=student, quiz=quiz, correct_answer=correct_answers, total_question=total_questions)
                    return redirect('students:completed_quiz', pk)
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'takeQuiz/students/take_quiz.html', {
        'quiz': quiz,
        'unanswered_questions_count':unanswered_questions_count,
        'question': question,
        'form': form,
    })


@login_required
@student_required
def confirm_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    return render(request, 'takeQuiz/students/confirm_quiz.html',{
        'quiz' : quiz,
    })


@login_required
@student_required
def completed_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk = pk)
    student = request.user.student
    if student.get_unanswered_questions(quiz).exists():
        return redirect('students:quiz_list')
    total_questions = quiz.questions.count()
    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
    return render(request, 'takeQuiz/students/completed_quiz.html', {
        'quiz': quiz,
        'total_questions': total_questions,
        'correct_answers' : correct_answers,
    })

takeQuiz/templates/takeQuiz/students/completed_quiz.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center; background-color: beige;">
    <h2>Thank you for taking the test.</h2>
    <h2>You have scored {{ correct_answers }} marks out of {{ total_questions }} in {{quiz.name}} Quiz</h2>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-dark">Return to homepage</a>
</div>
{% endblock %}

takeQuiz/templates/takeQuiz/students/confirm_quiz.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center; background-color: beige;">
    <h2>You are about to start a test.</h2>
    <h2>Please click the START button to start the test.</h2>
    <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-dark">Start</a>
</div>
{% endblock %}

takeQuiz/templates/takeQuiz/students/header.html
<h2 style="text-align: center;">Quizzes</h2>
<p class="text-muted">
    Subjects:{% for subject in user.student.subjects.all %} {{ subject.get_html_badge }}{% endfor %}
    <a href="{% url 'students:student_subjects' %}"><small><b>(Change subjects)</b></small></a>
</p>
<a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}"></a>
<a class="nav-link{% if active == 'quiztaken' %} active{% endif %}" href="{% url 'students:taken_quiz' %}"></a>

takeQuiz/templates/takeQuiz/students/quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'takeQuiz/students/header.html' with active='new' %}
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Total Questions</th>
          <th>Date Created</th>
          <th>Expiration Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          {% now "Y-m-d" as todays_date %}
          {% if todays_date < quiz.expiration_date|date:"Y-m-d" %}
            <tr>
              <td class="align-middle">{{ quiz.name }}</td>
              <td class="align-middle">{{ quiz.subject.name }}</td>
              <td class="align-middle">{{ quiz.questions.count }}</td>
              <td class="align-middle">{{ quiz.date_created }}</td>
              <td class="align-middle">{{ quiz.expiration_date }}</td>
              <td class="text-right">
                <!-- {% if quiz in taken_quizzes %}
                  <a href="{% url 'students:confirm_quiz' quiz.pk %}" class="btn btn-dark">Resume Test</a>
                {% else %} -->
                <a href="{% url 'students:confirm_quiz' quiz.pk %}" class="btn btn-dark">Start</a>
                <!-- {% endif %} -->
              </td>
            </tr>
            {% endif %}
        {% empty %}
          <tr>
            <td class="bg-light text-center" colspan="4">No quiz available right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

takeQuiz/templates/takeQuiz/students/subjects_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your subjects</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-dark">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-dark">Cancel</a>
  </form>
{% endblock %}

takeQuiz/templates/takeQuiz/students/take_quiz.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-dark">
      {% if unanswered_questions_count > 1 %}
        <span>Next</span>
      {% else %}
        <span>Submit</span>
      {% endif %}
    </button>
  </form>
{% endblock %}

takeQuiz/templates/takeQuiz/students/taken_quiz.html
{% extends 'base.html' %}

{% block content %}
  {% include 'takeQuiz/students/header.html' with active='quiztaken' %}
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Score</th>
          <th>Completed On</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.subject.name }}</td>
            <td>{{ taken_quiz.correct_answer }}/{{ taken_quiz.total_question }}</td>
            <td>{{ taken_quiz.date }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center" colspan="3">You haven't completed any quiz yet.<br>Go, Get started!</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}